baseURL = "https://www.robjwells.com"
languageCode = "en-gb"
title = "Primary Unit on Hugo"
theme = "robjwells-2020"
copyright = "This work is licensed under a Creative Commons Attribution 4.0 International License."
rssLimit = 10
[author]
name = "Rob Wells"

[permalinks]
posts = "/:year/:month/:slug"

[params]
description = "A blog by Rob Wells, mostly about computer stuff."
