baseURL = "https://www.robjwells.com"
languageCode = "en-gb"
title = "Primary Unit on Hugo"
theme = "robjwells-2020"

[permalinks]
posts = "/:year/:month/:slug"

[params]
description = "A blog by Rob Wells, mostly about computer stuff."
